"""added a source column

Revision ID: 850ff77ba982
Revises: a160249ad993
Create Date: 2026-06-16 03:44:11.655295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850ff77ba982'
down_revision: Union[str, Sequence[str], None] = 'a160249ad993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_prep_paths', sa.Column('generated_subject_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_job_prep_paths_generated_subject_id'), 'job_prep_paths', ['generated_subject_id'], unique=False)
    op.create_foreign_key(None, 'job_prep_paths', 'roadmap_subjects', ['generated_subject_id'], ['id'], ondelete='SET NULL')
    op.add_column('roadmap_subjects', sa.Column('source', sa.String(), nullable=False))
    op.add_column('roadmap_subjects', sa.Column('job_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_roadmap_subjects_job_id'), 'roadmap_subjects', ['job_id'], unique=False)
    op.create_foreign_key(None, 'roadmap_subjects', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmap_subjects', type_='foreignkey')
    op.drop_index(op.f('ix_roadmap_subjects_job_id'), table_name='roadmap_subjects')
    op.drop_column('roadmap_subjects', 'job_id')
    op.drop_column('roadmap_subjects', 'source')
    op.drop_constraint(None, 'job_prep_paths', type_='foreignkey')
    op.drop_index(op.f('ix_job_prep_paths_generated_subject_id'), table_name='job_prep_paths')
    op.drop_column('job_prep_paths', 'generated_subject_id')
    # ### end Alembic commands ###
