"""restructure_schema_to_new_architecture

Revision ID: cf22af15ca08
Revises: 850ff77ba982
Create Date: 2026-07-09 05:13:21.663581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf22af15ca08'
down_revision: Union[str, Sequence[str], None] = '850ff77ba982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('engine_type', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("engine_type IN ('job', 'prep', 'document', 'tracker')", name='ck_chat_sessions_engine_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_sessions_active', 'chat_sessions', ['user_id'], unique=False, postgresql_where='is_archived = false')
    op.create_index('idx_chat_sessions_updated', 'chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_index('idx_chat_sessions_user_engine', 'chat_sessions', ['user_id', 'engine_type'], unique=False)
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('access_token_jti', sa.Text(), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token_jti'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index('idx_sessions_access_token_jti', 'sessions', ['access_token_jti'], unique=False)
    op.create_index('idx_sessions_active', 'sessions', ['user_id'], unique=False, postgresql_where='revoked_at IS NULL')
    op.create_index('idx_sessions_refresh_token', 'sessions', ['refresh_token'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('normalised_md', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_profiles_user_id')
    )
    op.create_table('prep_roadmaps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_session_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('target_role', sa.Text(), nullable=False),
    sa.Column('target_company', sa.Text(), nullable=True),
    sa.Column('raw_roadmap', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_subject_index', sa.Integer(), nullable=False),
    sa.Column('current_topic_index', sa.Integer(), nullable=False),
    sa.Column('topic_mastery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed')", name='ck_prep_roadmaps_status'),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prep_roadmaps_chat_session', 'prep_roadmaps', ['chat_session_id'], unique=False)
    op.create_index('idx_prep_roadmaps_job', 'prep_roadmaps', ['job_id'], unique=False)
    op.create_index('idx_prep_roadmaps_user_id', 'prep_roadmaps', ['user_id'], unique=False)
    op.create_index('idx_prep_roadmaps_user_status', 'prep_roadmaps', ['user_id', 'status'], unique=False)
    op.drop_index(op.f('ix_roadmap_questions_subtopic_id'), table_name='roadmap_questions')
    op.drop_table('roadmap_questions')
    op.drop_index(op.f('ix_roadmap_subtopics_topic_id'), table_name='roadmap_subtopics')
    op.drop_table('roadmap_subtopics')
    op.drop_index(op.f('ix_job_prep_paths_generated_subject_id'), table_name='job_prep_paths')
    op.drop_index(op.f('ix_job_prep_paths_job_id'), table_name='job_prep_paths')
    op.drop_table('job_prep_paths')
    op.drop_index(op.f('ix_roadmap_topics_subject_id'), table_name='roadmap_topics')
    op.drop_table('roadmap_topics')
    op.drop_index(op.f('ix_roadmap_subjects_job_id'), table_name='roadmap_subjects')
    op.drop_table('roadmap_subjects')
    op.add_column('documents', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('chat_session_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('content_md', sa.Text(), nullable=False))
    op.alter_column('documents', 'job_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_documents_job_id'), table_name='documents')
    op.create_index('idx_documents_chat_session', 'documents', ['chat_session_id', 'type', 'version'], unique=False)
    op.create_index('idx_documents_job_id', 'documents', ['job_id'], unique=False)
    op.create_index('idx_documents_latest', 'documents', ['job_id', 'type', 'version'], unique=False)
    op.create_index('idx_documents_user_id', 'documents', ['user_id'], unique=False)
    op.drop_constraint(op.f('documents_job_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'chat_sessions', ['chat_session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'jobs', ['job_id'], ['id'], ondelete='SET NULL')
    op.drop_column('documents', 'content')
    op.add_column('jobs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index('idx_jobs_cursor', 'jobs', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index('idx_jobs_user_applied_date', 'jobs', ['user_id', 'applied_date'], unique=False)
    op.create_index('idx_jobs_user_follow_up', 'jobs', ['user_id', 'follow_up_date'], unique=False, postgresql_where='follow_up_date IS NOT NULL')
    op.create_index('idx_jobs_user_id', 'jobs', ['user_id'], unique=False)
    op.create_index('idx_jobs_user_status', 'jobs', ['user_id', 'status'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index('idx_jobs_user_status', table_name='jobs')
    op.drop_index('idx_jobs_user_id', table_name='jobs')
    op.drop_index('idx_jobs_user_follow_up', table_name='jobs', postgresql_where='follow_up_date IS NOT NULL')
    op.drop_index('idx_jobs_user_applied_date', table_name='jobs')
    op.drop_index('idx_jobs_cursor', table_name='jobs')
    op.drop_column('jobs', 'user_id')
    op.add_column('documents', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_job_id_fkey'), 'documents', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_documents_user_id', table_name='documents')
    op.drop_index('idx_documents_latest', table_name='documents')
    op.drop_index('idx_documents_job_id', table_name='documents')
    op.drop_index('idx_documents_chat_session', table_name='documents')
    op.create_index(op.f('ix_documents_job_id'), 'documents', ['job_id'], unique=False)
    op.alter_column('documents', 'job_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('documents', 'content_md')
    op.drop_column('documents', 'chat_session_id')
    op.drop_column('documents', 'user_id')
    op.create_table('roadmap_subjects',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('roadmap_subjects_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_subjects_pkey'))
    )
    op.create_index(op.f('ix_roadmap_subjects_job_id'), 'roadmap_subjects', ['job_id'], unique=False)
    op.create_table('roadmap_topics',
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['roadmap_subjects.id'], name=op.f('roadmap_topics_subject_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_topics_pkey'))
    )
    op.create_index(op.f('ix_roadmap_topics_subject_id'), 'roadmap_topics', ['subject_id'], unique=False)
    op.create_table('job_prep_paths',
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('strong_matches', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('needs_sharpening', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('roadmap_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('talking_points', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('likely_angles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('generated_subject_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['generated_subject_id'], ['roadmap_subjects.id'], name=op.f('job_prep_paths_generated_subject_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('job_prep_paths_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('job_prep_paths_pkey'))
    )
    op.create_index(op.f('ix_job_prep_paths_job_id'), 'job_prep_paths', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_prep_paths_generated_subject_id'), 'job_prep_paths', ['generated_subject_id'], unique=False)
    op.create_table('roadmap_subtopics',
    sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('concept', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_evidence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['roadmap_topics.id'], name=op.f('roadmap_subtopics_topic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_subtopics_pkey'))
    )
    op.create_index(op.f('ix_roadmap_subtopics_topic_id'), 'roadmap_subtopics', ['topic_id'], unique=False)
    op.create_table('roadmap_questions',
    sa.Column('subtopic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subtopic_id'], ['roadmap_subtopics.id'], name=op.f('roadmap_questions_subtopic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_questions_pkey'))
    )
    op.create_index(op.f('ix_roadmap_questions_subtopic_id'), 'roadmap_questions', ['subtopic_id'], unique=False)
    op.drop_index('idx_prep_roadmaps_user_status', table_name='prep_roadmaps')
    op.drop_index('idx_prep_roadmaps_user_id', table_name='prep_roadmaps')
    op.drop_index('idx_prep_roadmaps_job', table_name='prep_roadmaps')
    op.drop_index('idx_prep_roadmaps_chat_session', table_name='prep_roadmaps')
    op.drop_table('prep_roadmaps')
    op.drop_table('user_profiles')
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_index('idx_sessions_refresh_token', table_name='sessions')
    op.drop_index('idx_sessions_active', table_name='sessions', postgresql_where='revoked_at IS NULL')
    op.drop_index('idx_sessions_access_token_jti', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_user_engine', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_updated', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_active', table_name='chat_sessions', postgresql_where='is_archived = false')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
